TCBMTGWebShop/Pages/Games/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TCBMTGWebShop.Models.Domain;
using TCBMTGWebShop.Data;
using TCBMTGWebShop.Models.ViewModels;

namespace TCBMTGWebShop.Pages.Games
{
    public class AddModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;

        public AddModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [BindProperty]
        public AddGameViewModel AddGameRequest { get; set; }
        public void OnGet()
        {
        }

        public void OnPost()
        {
            // Convert View to Domain
            var GameDomainModel = new ProductGame
            {
                productGame = AddGameRequest.productGame,
                GameCreator = AddGameRequest.GameCreator,

            };


            dbContext.Games.Add(GameDomainModel);

            dbContext.SaveChanges();

            ViewData["Message"] = "Game Created Succesfully";
        }
    }
}

TCBMTGWebShop/Pages/Games/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using TCBMTGWebShop.Data;
using TCBMTGWebShop.Models.Domain;
using TCBMTGWebShop.Models.ViewModels;

namespace TCBMTGWebShop.Pages.Games
{
    public class EditModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;

        [BindProperty]
        public EditGameViewModel EditGameViewModel { get; set; }
        public EditModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public void OnGet(Guid id)
        {
            var Game = dbContext.Games.Find(id);

            if (Game != null)
            {
                //Convert Domain to View Model
                EditGameViewModel = new EditGameViewModel()
                {
                    Id = Game.Id,
                    productGame = Game.productGame,
                    GameCreator = Game.GameCreator,
                };
            }
        }
        public void OnPostUpdate()
        {

            if (EditGameViewModel != null)
            {
                var existingGame = dbContext.Games.Find(EditGameViewModel.Id);


                if (existingGame != null)
                {
                    //Convert View Model to Domain Model

                    existingGame.productGame = EditGameViewModel.productGame;
                    existingGame.GameCreator = EditGameViewModel.GameCreator;

                    dbContext.SaveChanges();

                    ViewData["Message"] = "Game Modified Succesfully";
                }
            }
        }
        public IActionResult OnPostDelete()
        {
            var ExistingGame = dbContext.Games.Find(EditGameViewModel.Id);

            if (ExistingGame != null)
            {
                dbContext.Games.Remove(ExistingGame);
                dbContext.SaveChanges();

                return RedirectToPage("/Games/List");
            }

            return Page();
        }
    }
}

TCBMTGWebShop/Pages/Games/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TCBMTGWebShop.Data;

namespace TCBMTGWebShop.Pages.Games
{
    public class ListModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;
        public List<Models.Domain.ProductGame> Games { get; set; }
        public ListModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet()
        {
            Games = dbContext.Games.ToList();
        }
    }
}

TCBMTGWebShop/Pages/Products/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TCBMTGWebShop.Models.Domain;
using TCBMTGWebShop.Data;
using TCBMTGWebShop.Models.ViewModels;

namespace TCBMTGWebShop.Pages.Products
{
    public class AddModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;

        public AddModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public List<ProductGame> Games { get; set; }
        public List<productType> Types { get; set; }


        [BindProperty]

        public AddProductViewModel AddProductRequest { get; set; }
        public void OnGet()
        {
            Games = dbContext.Games.ToList();
            Types = dbContext.Types.ToList();
        }

        public void OnPost() 
        {
            Games = dbContext.Games.ToList();
            Types = dbContext.Types.ToList();
            // Convert View to Domain
            var productDomainModel = new Product
            {
                ProductName = AddProductRequest.ProductName,
                ProductDescription = AddProductRequest.ProductDescription,
                ProductType = AddProductRequest.ProductType,
                productGame = AddProductRequest.productGame,
                ProductPrice = AddProductRequest.ProductPrice,
                ProductQuantity = AddProductRequest.ProductQuantity
            };


            dbContext.Products.Add(productDomainModel);
            dbContext.SaveChanges();

            ViewData["Message"] = "Product Created Succesfully";
        }
    }
}

TCBMTGWebShop/Pages/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using TCBMTGWebShop.Data;
using TCBMTGWebShop.Models.Domain;
using TCBMTGWebShop.Models.ViewModels;

namespace TCBMTGWebShop.Pages.Products
{
    public class EditModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;

        public List<ProductGame> Games { get; set; }
        public List<productType> Types { get; set; }

        [BindProperty]
        public EditProductViewModel EditProductViewModel { get; set; } 
        public EditModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public void OnGet(Guid id)
        {
            var Product = dbContext.Products.Find(id);
            Games = dbContext.Games.ToList();
            Types = dbContext.Types.ToList();

            if (Product != null) 
            {
                //Convert Domain to View Model
                EditProductViewModel = new EditProductViewModel()
                {
                    Id = Product.Id,
                    ProductName = Product.ProductName,
                    ProductDescription = Product.ProductDescription,
                    ProductType = Product.ProductType,
                    productGame = Product.productGame,
                    ProductPrice = Product.ProductPrice,
                    ProductQuantity = Product.ProductQuantity
                };
            }
        }
        public void OnPostUpdate()
        {
            Games = dbContext.Games.ToList();
            Types = dbContext.Types.ToList();
            if (EditProductViewModel != null) 
            {
                var existingProduct = dbContext.Products.Find(EditProductViewModel.Id);


                if (existingProduct != null)
                {
                    //Convert View Model to Domain Model
                    existingProduct.ProductName = EditProductViewModel.ProductName;
                    existingProduct.ProductDescription = EditProductViewModel.ProductDescription;
                    existingProduct.ProductType = EditProductViewModel.ProductType;
                    existingProduct.productGame = EditProductViewModel.productGame;
                    existingProduct.ProductPrice = EditProductViewModel.ProductPrice;
                    existingProduct.ProductQuantity = EditProductViewModel.ProductQuantity;

                    dbContext.SaveChanges();

                    ViewData["Message"] = "Product Modified Succesfully";
                }
            }
        }
        public IActionResult OnPostDelete()
        {
            var ExistingProduct = dbContext.Products.Find(EditProductViewModel.Id);
            Games = dbContext.Games.ToList();
            Types = dbContext.Types.ToList();

            if (ExistingProduct != null){
                dbContext.Products.Remove(ExistingProduct);
                dbContext.SaveChanges();

                return RedirectToPage("/Products/List");
            }

            return Page();
        }
    }
}

TCBMTGWebShop/Pages/Products/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TCBMTGWebShop.Data;

namespace TCBMTGWebShop.Pages.Products
{
    public class ListModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;
        public List<Models.Domain.Product> Products { get; set; }
        public ListModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet()
        {
            Products = dbContext.Products.ToList();
        }
    }
}

TCBMTGWebShop/Pages/Types/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TCBMTGWebShop.Models.Domain;
using TCBMTGWebShop.Data;
using TCBMTGWebShop.Models.ViewModels;

namespace TCBMTGWebShop.Pages.Types
{
    public class AddModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;

        public AddModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [BindProperty]
        public AddTypeViewModel AddTypeRequest { get; set; }
        public void OnGet()
        {
        }

        public void OnPost() 
        {
            // Convert View to Domain
            var typeDomainModel = new productType
            {
                ProductType = AddTypeRequest.ProductType,
                TypeStorageSpace = AddTypeRequest.TypeStorageSpace,

            };


            dbContext.Types.Add(typeDomainModel);

            dbContext.SaveChanges();

            ViewData["Message"] = "Type Created Succesfully";
        }
    }
}

TCBMTGWebShop/Pages/Types/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using TCBMTGWebShop.Data;
using TCBMTGWebShop.Models.Domain;
using TCBMTGWebShop.Models.ViewModels;

namespace TCBMTGWebShop.Pages.Types
{
    public class EditModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;

        [BindProperty]
        public EditTypeViewModel EditTypeViewModel { get; set; } 
        public EditModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public void OnGet(Guid id)
        {
            var Type = dbContext.Types.Find(id);

            if (Type != null) 
            {
                //Convert Domain to View Model
                EditTypeViewModel = new EditTypeViewModel()
                {
                    Id = Type.Id,
                    ProductType = Type.ProductType,
                    TypeStorageSpace = Type.TypeStorageSpace,
                };
            }
        }
        public void OnPostUpdate()
        {

            if (EditTypeViewModel != null) 
            {
                var existingType = dbContext.Types.Find(EditTypeViewModel.Id);


                if (existingType != null)
                {
                    //Convert View Model to Domain Model

                    existingType.ProductType = EditTypeViewModel.ProductType;
                    existingType.TypeStorageSpace = EditTypeViewModel.TypeStorageSpace;

                    dbContext.SaveChanges();

                    ViewData["Message"] = "Type Modified Succesfully";
                }
            }
        }
        public IActionResult OnPostDelete()
        {
            var ExistingType = dbContext.Types.Find(EditTypeViewModel.Id);

            if(ExistingType != null){
                dbContext.Types.Remove(ExistingType);
                dbContext.SaveChanges();

                return RedirectToPage("/Types/List");
            }

            return Page();
        }
    }
}

TCBMTGWebShop/Pages/Types/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TCBMTGWebShop.Data;

namespace TCBMTGWebShop.Pages.Types
{
    public class ListModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;
        public List<Models.Domain.productType> Types { get; set; }
        public ListModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet()
        {
            Types = dbContext.Types.ToList();
        }
    }
}

TCBMTGWebShop/Pages/Types/Add.cshtml
@page
@model TCBMTGWebShop.Pages.Types.AddModel

@{
    var message = ViewData["Message"]?.ToString();
}

<form method="post">

<h1 class="mb-3">Add New Product Type</h1>

@if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
        @message
        </div>
    }



<div class="mb-3">
    <label class="form-label">Product Type Name</label>
        <input type="text" class="form-control" asp-for="AddTypeRequest.ProductType"/>
</div>

    <div class="mb-3">
        <label class="form-label">Product Type Storage Location</label>
        <input type="text" class="form-control" asp-for="AddTypeRequest.TypeStorageSpace" />
    </div>

    <div class="mb-3 d-flex justify-content-between">
    <button type="submit" class="btn btn-primary" href="/Types/List">Save</button>
    <a id="btnList" class="btn btn-dark" href="/Types/List">Back to Overview</a>
</div>

</form>

TCBMTGWebShop/Pages/Types/Edit.cshtml
@page "{id:Guid}"
@model TCBMTGWebShop.Pages.Types.EditModel
@{
    var message = ViewData["Message"]?.ToString();
}

<form method="post">

<h1 class="mb-3">Edit Product Type</h1>

    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }
    <div class="mb-3">
    <label class="form-label">Product ID</label>
    <input type="text" class="form-control" asp-for="EditTypeViewModel.Id" readonly/>
</div>

<div class="mb-3">
    <label class="form-label">Product Description</label>
        <input type="text" class="form-control" asp-for="EditTypeViewModel.TypeStorageSpace" />
</div>

<div class="mb-3">
    <label class="form-label">Product Type</label>
        <input type="text" class="form-control" asp-for="EditTypeViewModel.ProductType" />
</div>

    <div class="mb-3 d-flex justify-content-between">
        <button type="submit" class="btn btn-primary" asp-page-handler="Update">
            Update
        </button>
        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this Product?')" asp-page-handler="Delete">
            Delete
        </button>
    </div>

</form>

TCBMTGWebShop/Pages/Types/List.cshtml
@page
@model TCBMTGWebShop.Pages.Types.ListModel
@{
}


<h1 class="mb-3">List of Types</h1>

@if (Model.Types != null && Model.Types.Any() )
{

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product Type</th>
                <th>Type Storage Space</th>
                <th><a type="" id="btnAdd" value="Add" class="btn btn-primary" href="/Types/Add">Add Product</a></th>

            </tr>

        </thead>
        <tbody>
            @foreach (var Type in Model.Types)
            {
                <tr>
                    <td>@Type.Id</td>
                    <td>@Type.ProductType</td>
                    <td>@Type.TypeStorageSpace</td>
                    <td>
                        <a href="/Types/Edit/@Type.Id" class="btn btn-dark">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
            <table class="table">
        <thead>
                <tr>
                    <th>Id</th>
                    <th>Product Type</th>
                    <th>Type Storage Space</th>
                    <th><a type="" id="btnAdd" value="Add" class="btn btn-primary" href="/Types/Add">Add Type</a></th>

                </tr>

            </thead>


    <p>No Types Found</p>
    </table>
}